name: generate pacman animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: generate pacman-contribution-graph.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-pacman.svg
            dist/github-contribution-grid-pacman-dark.svg?palette=github-dark
        env:
            GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}


      - name: push github-contribution-grid-pacman.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
            GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}

